2022-03-08 00:44:40,496 INFO    MainThread:3014 [wandb_setup.py:_flush():75] Loading settings from /home/lieberze/.config/wandb/settings
2022-03-08 00:44:40,496 INFO    MainThread:3014 [wandb_setup.py:_flush():75] Loading settings from /home/lieberze/DP/Thesis/06_adapter/wandb/settings
2022-03-08 00:44:40,497 INFO    MainThread:3014 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-03-08 00:44:40,497 INFO    MainThread:3014 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-03-08 00:44:40,497 INFO    MainThread:3014 [wandb_init.py:_log_setup():386] Logging user logs to /home/lieberze/DP/Thesis/06_adapter/wandb/run-20220308_004440-qrnxqcwy/logs/debug.log
2022-03-08 00:44:40,497 INFO    MainThread:3014 [wandb_init.py:_log_setup():387] Logging internal logs to /home/lieberze/DP/Thesis/06_adapter/wandb/run-20220308_004440-qrnxqcwy/logs/debug-internal.log
2022-03-08 00:44:40,497 INFO    MainThread:3014 [wandb_init.py:_jupyter_setup():336] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7faf0205d7f0>
2022-03-08 00:44:40,498 INFO    MainThread:3014 [wandb_init.py:init():420] calling init triggers
2022-03-08 00:44:40,498 INFO    MainThread:3014 [wandb_init.py:init():427] wandb.init called with sweep_config: {}
config: {}
2022-03-08 00:44:40,498 INFO    MainThread:3014 [wandb_init.py:init():442] re-initializing run, found existing run on stack: 1qd2ytjf
2022-03-08 00:44:40,500 INFO    MainThread:3014 [wandb_run.py:finish():1468] finishing run liebelife/adapter_CV_3x3/1qd2ytjf
2022-03-08 00:44:40,501 INFO    MainThread:3014 [wandb_run.py:_atexit_cleanup():1797] got exitcode: 0
2022-03-08 00:44:40,502 INFO    MainThread:3014 [wandb_run.py:_restore():1769] restore
2022-03-08 00:44:41,286 INFO    MainThread:3014 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 880
  total_bytes: 880
}

2022-03-08 00:44:41,407 INFO    MainThread:3014 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 880
  total_bytes: 880
}

2022-03-08 00:44:41,617 INFO    MainThread:3014 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 880
  total_bytes: 880
}

2022-03-08 00:44:41,816 INFO    MainThread:3014 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 880
  total_bytes: 9304
}

2022-03-08 00:44:41,926 INFO    MainThread:3014 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 880
  total_bytes: 17037
}

2022-03-08 00:44:42,040 INFO    MainThread:3014 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 880
  total_bytes: 17037
}

2022-03-08 00:44:42,142 INFO    MainThread:3014 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17037
  total_bytes: 17037
}

2022-03-08 00:44:42,246 INFO    MainThread:3014 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17037
  total_bytes: 17037
}

2022-03-08 00:44:42,348 INFO    MainThread:3014 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17037
  total_bytes: 17037
}

2022-03-08 00:44:42,450 INFO    MainThread:3014 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17037
  total_bytes: 17037
}

2022-03-08 00:44:42,552 INFO    MainThread:3014 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17037
  total_bytes: 17037
}

2022-03-08 00:44:43,095 INFO    MainThread:3014 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17037
  total_bytes: 17037
}

2022-03-08 00:44:43,514 INFO    MainThread:3014 [wandb_run.py:_wait_for_finish():1929] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17037
  total_bytes: 17037
}
local_info {
}

2022-03-08 00:44:44,953 INFO    MainThread:3014 [wandb_run.py:_append_files():2194] logging synced files
2022-03-08 00:44:44,962 INFO    MainThread:3014 [wandb_init.py:init():471] starting backend
2022-03-08 00:44:44,962 INFO    MainThread:3014 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-03-08 00:44:44,965 INFO    MainThread:3014 [backend.py:ensure_launched():219] starting backend process...
2022-03-08 00:44:45,070 INFO    MainThread:3014 [backend.py:ensure_launched():225] started backend process with pid: 4611
2022-03-08 00:44:45,072 INFO    MainThread:3014 [wandb_init.py:init():480] backend started and connected
2022-03-08 00:44:45,117 INFO    MainThread:3014 [wandb_run.py:_label_probe_notebook():921] probe notebook
2022-03-08 00:44:45,117 INFO    MainThread:3014 [wandb_run.py:_label_probe_notebook():931] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-03-08 00:44:45,117 INFO    MainThread:3014 [wandb_init.py:init():550] updated telemetry
2022-03-08 00:44:45,287 INFO    MainThread:3014 [wandb_init.py:init():581] communicating current version
2022-03-08 00:44:46,637 INFO    MainThread:3014 [wandb_init.py:init():586] got version response upgrade_message: "wandb version 0.12.11 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-03-08 00:44:46,639 INFO    MainThread:3014 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-03-08 00:44:46,850 INFO    MainThread:3014 [wandb_init.py:init():624] starting run threads in backend
2022-03-08 00:44:51,864 INFO    MainThread:3014 [wandb_run.py:_console_start():1827] atexit reg
2022-03-08 00:44:51,865 INFO    MainThread:3014 [wandb_run.py:_redirect():1701] redirect: SettingsConsole.WRAP
2022-03-08 00:44:51,866 INFO    MainThread:3014 [wandb_run.py:_redirect():1738] Wrapping output streams.
2022-03-08 00:44:51,867 INFO    MainThread:3014 [wandb_run.py:_redirect():1762] Redirects installed.
2022-03-08 00:44:51,867 INFO    MainThread:3014 [wandb_init.py:init():651] run started, returning control to user process
2022-03-08 00:44:53,557 INFO    MainThread:3014 [wandb_init.py:_pause_backend():299] pausing backend
2022-03-08 00:44:53,558 INFO    MainThread:3014 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-03-08 00:45:00,061 INFO    MainThread:3014 [wandb_init.py:_resume_backend():308] resuming backend
2022-03-08 00:45:00,095 INFO    MainThread:3014 [wandb_setup.py:_flush():75] Loading settings from /home/lieberze/.config/wandb/settings
2022-03-08 00:45:00,096 INFO    MainThread:3014 [wandb_setup.py:_flush():75] Loading settings from /home/lieberze/DP/Thesis/06_adapter/wandb/settings
2022-03-08 00:45:00,096 INFO    MainThread:3014 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-03-08 00:45:00,096 INFO    MainThread:3014 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-03-08 00:45:00,096 INFO    MainThread:3014 [wandb_init.py:_log_setup():386] Logging user logs to /home/lieberze/DP/Thesis/06_adapter/wandb/run-20220308_004500-1g859l0f/logs/debug.log
2022-03-08 00:45:00,096 INFO    MainThread:3014 [wandb_init.py:_log_setup():387] Logging internal logs to /home/lieberze/DP/Thesis/06_adapter/wandb/run-20220308_004500-1g859l0f/logs/debug-internal.log
2022-03-08 00:45:00,097 INFO    MainThread:3014 [wandb_init.py:init():420] calling init triggers
2022-03-08 00:45:00,097 INFO    MainThread:3014 [wandb_init.py:init():427] wandb.init called with sweep_config: {}
config: {}
2022-03-08 00:45:00,097 INFO    MainThread:3014 [wandb_init.py:init():442] re-initializing run, found existing run on stack: qrnxqcwy
2022-03-08 00:45:00,100 INFO    MainThread:3014 [wandb_run.py:finish():1468] finishing run liebelife/adapter_CV_3x3/qrnxqcwy
2022-03-08 00:45:00,101 INFO    MainThread:3014 [jupyter.py:save_history():429] not saving jupyter history
2022-03-08 00:45:00,101 INFO    MainThread:3014 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-03-08 00:45:00,101 INFO    MainThread:3014 [wandb_init.py:_jupyter_teardown():318] cleaning up jupyter logic
2022-03-08 00:45:00,101 INFO    MainThread:3014 [wandb_run.py:_atexit_cleanup():1797] got exitcode: 0
2022-03-08 00:45:00,103 INFO    MainThread:3014 [wandb_run.py:_restore():1769] restore
2022-03-08 00:45:00,910 INFO    MainThread:3014 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 880
  total_bytes: 880
}

2022-03-08 00:45:01,077 INFO    MainThread:3014 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 880
  total_bytes: 880
}

2022-03-08 00:45:01,305 INFO    MainThread:3014 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 880
  total_bytes: 880
}

2022-03-08 00:45:01,976 INFO    MainThread:3014 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 880
  total_bytes: 9303
}

2022-03-08 00:45:02,081 INFO    MainThread:3014 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 880
  total_bytes: 17036
}

2022-03-08 00:45:02,202 INFO    MainThread:3014 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 880
  total_bytes: 17036
}

2022-03-08 00:45:02,305 INFO    MainThread:3014 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17036
  total_bytes: 17036
}

2022-03-08 00:45:02,409 INFO    MainThread:3014 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17036
  total_bytes: 17036
}

2022-03-08 00:45:02,511 INFO    MainThread:3014 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17036
  total_bytes: 17036
}

2022-03-08 00:45:02,614 INFO    MainThread:3014 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17036
  total_bytes: 17036
}

2022-03-08 00:45:02,716 INFO    MainThread:3014 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17036
  total_bytes: 17036
}

2022-03-08 00:45:02,818 INFO    MainThread:3014 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17036
  total_bytes: 17036
}

2022-03-08 00:45:03,316 INFO    MainThread:3014 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17036
  total_bytes: 17036
}

2022-03-08 00:45:03,773 INFO    MainThread:3014 [wandb_run.py:_wait_for_finish():1929] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17036
  total_bytes: 17036
}
local_info {
}

2022-03-08 00:45:05,227 INFO    MainThread:3014 [wandb_run.py:_append_files():2194] logging synced files
